export const ROLES = ['ADMIN', 'INSPECTOR', 'MAINTENANCE', 'VIEWER']
export const DEMO_ACTOR_ID = '00000000-0000-0000-0000-000000000001'
export const ASSET_TYPES = ['ROAD', 'BRIDGE', 'BUILDING']
export const ASSET_STATUSES = ['PLANNED', 'UNDER_CONSTRUCTION', 'OPERATIONAL', 'MAINTENANCE', 'RETIRED']
export const DEFECT_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
export const DEFECT_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED']
export const MAINTENANCE_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
export const MAINTENANCE_STATUSES = ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED']

export const LIFECYCLE_TRANSITIONS = {
  PLANNED: ['UNDER_CONSTRUCTION'],
  UNDER_CONSTRUCTION: ['OPERATIONAL'],
  OPERATIONAL: ['MAINTENANCE', 'RETIRED'],
  MAINTENANCE: ['OPERATIONAL'],
  RETIRED: [],
}

export const LIFECYCLE_ALLOWED_ROLES = {
  PLANNED: { UNDER_CONSTRUCTION: ['ADMIN'] },
  UNDER_CONSTRUCTION: { OPERATIONAL: ['ADMIN'] },
  OPERATIONAL: { MAINTENANCE: ['ADMIN'], RETIRED: ['ADMIN'] },
  MAINTENANCE: { OPERATIONAL: ['ADMIN'] },
  RETIRED: {},
}