import { useState } from "react";
import { createAsset } from "../../api/assets";

export function AssetForm({ onClose, onSaved }) {
  const [form, setForm] = useState({ asset_code: "", name: "", type: "ROAD", location_lat: "", location_lng: "", criticality: "" }); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await createAsset({ ...form, location_lat: Number(form.location_lat), location_lng: Number(form.location_lng), criticality: form.criticality ? Number(form.criticality) : undefined }); onSaved(); onClose(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <Modal title="Register infrastructure asset" onClose={onClose}><form className="form-grid" onSubmit={submit}><Field label="Asset code" value={form.asset_code} onChange={(v) => setForm({ ...form, asset_code: v })} required /><Field label="Name" value={form.name} onChange={(v) => setForm({ ...form, name: v })} required /><label>Type<select className="select" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option>ROAD</option><option>BRIDGE</option><option>BUILDING</option></select></label><Field label="Latitude" type="number" value={form.location_lat} onChange={(v) => setForm({ ...form, location_lat: v })} required /><Field label="Longitude" type="number" value={form.location_lng} onChange={(v) => setForm({ ...form, location_lng: v })} required /><Field label="Criticality (1–5)" type="number" value={form.criticality} onChange={(v) => setForm({ ...form, criticality: v })} /><div className="form-actions"><button type="button" className="button button-ghost" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? "Saving..." : "Create asset"}</button></div>{error && <div className="form-error">{error}</div>}</form></Modal>;
}
function Field({ label, value, onChange, type = "text", required }) { return <label>{label}<input className="input" type={type} value={value} required={required} onChange={(e) => onChange(e.target.value)} /></label>; }
function Modal({ title, onClose, children }) { return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section className="modal"><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose}>×</button></div>{children}</section></div>; }
